
package com.lftechnology.gmt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param transfer
     * @param receiver
     * @param pass
     * @param sender
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "InsertTransaction", action = "http://tempuri.org/IService1/InsertTransaction")
    @WebResult(name = "InsertTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertTransaction", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.InsertTransaction")
    @ResponseWrapper(localName = "InsertTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.InsertTransactionResponse")
    public WsResponse insertTransaction(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        WsSender sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        WsReceiver receiver,
        @WebParam(name = "transfer", targetNamespace = "http://tempuri.org/")
        WsTransferInfo transfer);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsPaidTransactions
     */
    @WebMethod(operationName = "GetPaidTransactions", action = "http://tempuri.org/IService1/GetPaidTransactions")
    @WebResult(name = "GetPaidTransactionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPaidTransactions", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetPaidTransactions")
    @ResponseWrapper(localName = "GetPaidTransactionsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetPaidTransactionsResponse")
    public ArrayOfwsPaidTransactions getPaidTransactions(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ConfirmPayment", action = "http://tempuri.org/IService1/ConfirmPayment")
    @WebResult(name = "ConfirmPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmPayment", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmPayment")
    @ResponseWrapper(localName = "ConfirmPaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmPaymentResponse")
    public WsResponse confirmPayment(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param comment
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "RequestCancellation", action = "http://tempuri.org/IService1/RequestCancellation")
    @WebResult(name = "RequestCancellationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestCancellation", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.RequestCancellation")
    @ResponseWrapper(localName = "RequestCancellationResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.RequestCancellationResponse")
    public WsResponse requestCancellation(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt,
        @WebParam(name = "comment", targetNamespace = "http://tempuri.org/")
        String comment);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsVoidTransactions
     */
    @WebMethod(operationName = "GetCancelledTransactions", action = "http://tempuri.org/IService1/GetCancelledTransactions")
    @WebResult(name = "GetCancelledTransactionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCancelledTransactions", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetCancelledTransactions")
    @ResponseWrapper(localName = "GetCancelledTransactionsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetCancelledTransactionsResponse")
    public ArrayOfwsVoidTransactions getCancelledTransactions(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ConfirmCancellation", action = "http://tempuri.org/IService1/ConfirmCancellation")
    @WebResult(name = "ConfirmCancellationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmCancellation", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmCancellation")
    @ResponseWrapper(localName = "ConfirmCancellationResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmCancellationResponse")
    public WsResponse confirmCancellation(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param data
     * @param pass
     * @param alias
     * @param receipt
     * @param comment
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "RequestModification", action = "http://tempuri.org/IService1/RequestModification")
    @WebResult(name = "RequestModificationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestModification", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.RequestModification")
    @ResponseWrapper(localName = "RequestModificationResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.RequestModificationResponse")
    public WsResponse requestModification(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt,
        @WebParam(name = "comment", targetNamespace = "http://tempuri.org/")
        String comment,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        WsChangeRequestData data);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsModifiedTransactions
     */
    @WebMethod(operationName = "GetModifiedTransactions", action = "http://tempuri.org/IService1/GetModifiedTransactions")
    @WebResult(name = "GetModifiedTransactionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetModifiedTransactions", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetModifiedTransactions")
    @ResponseWrapper(localName = "GetModifiedTransactionsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetModifiedTransactionsResponse")
    public ArrayOfwsModifiedTransactions getModifiedTransactions(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ConfirmModification", action = "http://tempuri.org/IService1/ConfirmModification")
    @WebResult(name = "ConfirmModificationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmModification", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmModification")
    @ResponseWrapper(localName = "ConfirmModificationResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmModificationResponse")
    public WsResponse confirmModification(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsReleasedTransactions
     */
    @WebMethod(operationName = "GetReleasedTransactions", action = "http://tempuri.org/IService1/GetReleasedTransactions")
    @WebResult(name = "GetReleasedTransactionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReleasedTransactions", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetReleasedTransactions")
    @ResponseWrapper(localName = "GetReleasedTransactionsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetReleasedTransactionsResponse")
    public ArrayOfwsReleasedTransactions getReleasedTransactions(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ConfirmRelease", action = "http://tempuri.org/IService1/ConfirmRelease")
    @WebResult(name = "ConfirmReleaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmRelease", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmRelease")
    @ResponseWrapper(localName = "ConfirmReleaseResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmReleaseResponse")
    public WsResponse confirmRelease(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsCollectedAch
     */
    @WebMethod(operationName = "GetClearedAchTransactions", action = "http://tempuri.org/IService1/GetClearedAchTransactions")
    @WebResult(name = "GetClearedAchTransactionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClearedAchTransactions", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetClearedAchTransactions")
    @ResponseWrapper(localName = "GetClearedAchTransactionsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetClearedAchTransactionsResponse")
    public ArrayOfwsCollectedAch getClearedAchTransactions(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ConfirmCollection", action = "http://tempuri.org/IService1/ConfirmCollection")
    @WebResult(name = "ConfirmCollectionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmCollection", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmCollection")
    @ResponseWrapper(localName = "ConfirmCollectionResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ConfirmCollectionResponse")
    public WsResponse confirmCollection(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsNotifications
     */
    @WebMethod(operationName = "GetNotifications", action = "http://tempuri.org/IService1/GetNotifications")
    @WebResult(name = "GetNotificationsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNotifications", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetNotifications")
    @ResponseWrapper(localName = "GetNotificationsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetNotificationsResponse")
    public ArrayOfwsNotifications getNotifications(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsAchStatus
     */
    @WebMethod(operationName = "GetAchStatus", action = "http://tempuri.org/IService1/GetAchStatus")
    @WebResult(name = "GetAchStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAchStatus", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetAchStatus")
    @ResponseWrapper(localName = "GetAchStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetAchStatusResponse")
    public WsAchStatus getAchStatus(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param alias
     * @param receipt
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsStatus
     */
    @WebMethod(operationName = "GetTransactionStatus", action = "http://tempuri.org/IService1/GetTransactionStatus")
    @WebResult(name = "GetTransactionStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTransactionStatus", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetTransactionStatus")
    @ResponseWrapper(localName = "GetTransactionStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetTransactionStatusResponse")
    public WsStatus getTransactionStatus(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt);

    /**
     * 
     * @param pass
     * @param service
     * @param alias
     * @param currency
     * @param user
     * @param payer
     * @param mts
     * @return
     *     returns com.lftechnology.gmt.WsExRate
     */
    @WebMethod(operationName = "GetSingleExchangeRate", action = "http://tempuri.org/IService1/GetSingleExchangeRate")
    @WebResult(name = "GetSingleExchangeRateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSingleExchangeRate", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetSingleExchangeRate")
    @ResponseWrapper(localName = "GetSingleExchangeRateResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetSingleExchangeRateResponse")
    public WsExRate getSingleExchangeRate(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "payer", targetNamespace = "http://tempuri.org/")
        String payer,
        @WebParam(name = "mts", targetNamespace = "http://tempuri.org/")
        String mts,
        @WebParam(name = "service", targetNamespace = "http://tempuri.org/")
        String service,
        @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
        String currency);

    /**
     * 
     * @param pass
     * @param alias
     * @param currency
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsExRateList
     */
    @WebMethod(operationName = "GetExchangeRates", action = "http://tempuri.org/IService1/GetExchangeRates")
    @WebResult(name = "GetExchangeRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExchangeRates", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetExchangeRates")
    @ResponseWrapper(localName = "GetExchangeRatesResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetExchangeRatesResponse")
    public ArrayOfwsExRateList getExchangeRates(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "currency", targetNamespace = "http://tempuri.org/")
        String currency);

    /**
     * 
     * @param lastName
     * @param firstName
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsOfac
     */
    @WebMethod(operationName = "OfacVerification", action = "http://tempuri.org/IService1/OfacVerification")
    @WebResult(name = "OfacVerificationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OfacVerification", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.OfacVerification")
    @ResponseWrapper(localName = "OfacVerificationResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.OfacVerificationResponse")
    public WsOfac ofacVerification(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "lastName", targetNamespace = "http://tempuri.org/")
        String lastName,
        @WebParam(name = "firstName", targetNamespace = "http://tempuri.org/")
        String firstName);

    /**
     * 
     * @param transfer
     * @param receiver
     * @param pass
     * @param sender
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResponse
     */
    @WebMethod(operationName = "ComplianceCheck", action = "http://tempuri.org/IService1/ComplianceCheck")
    @WebResult(name = "ComplianceCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ComplianceCheck", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ComplianceCheck")
    @ResponseWrapper(localName = "ComplianceCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.ComplianceCheckResponse")
    public WsResponse complianceCheck(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        WsSender sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        WsReceiver receiver,
        @WebParam(name = "transfer", targetNamespace = "http://tempuri.org/")
        WsTransferInfo transfer);

    /**
     * 
     * @param score
     * @param pass
     * @param alias
     * @param receipt
     * @param comment
     * @param passed
     * @param user
     * @return
     *     returns com.lftechnology.gmt.WsResult
     */
    @WebMethod(operationName = "SetVerified", action = "http://tempuri.org/IService1/SetVerified")
    @WebResult(name = "SetVerifiedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetVerified", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.SetVerified")
    @ResponseWrapper(localName = "SetVerifiedResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.SetVerifiedResponse")
    public WsResult setVerified(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "receipt", targetNamespace = "http://tempuri.org/")
        String receipt,
        @WebParam(name = "passed", targetNamespace = "http://tempuri.org/")
        Boolean passed,
        @WebParam(name = "score", targetNamespace = "http://tempuri.org/")
        String score,
        @WebParam(name = "comment", targetNamespace = "http://tempuri.org/")
        String comment);

    /**
     * 
     * @param billerId
     * @param firstname
     * @param pass
     * @param alias
     * @param user
     * @param account
     * @param lastname
     * @return
     *     returns com.lftechnology.gmt.WsBillInfo
     */
    @WebMethod(operationName = "BillConsult", action = "http://tempuri.org/IService1/BillConsult")
    @WebResult(name = "BillConsultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BillConsult", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.BillConsult")
    @ResponseWrapper(localName = "BillConsultResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.BillConsultResponse")
    public WsBillInfo billConsult(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "billerId", targetNamespace = "http://tempuri.org/")
        String billerId,
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "firstname", targetNamespace = "http://tempuri.org/")
        String firstname,
        @WebParam(name = "lastname", targetNamespace = "http://tempuri.org/")
        String lastname);

    /**
     * 
     * @param pass
     * @param countryCode
     * @param payerCode
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.ArrayOfwsSelectPayersByCountryCodeResult
     */
    @WebMethod(operationName = "PayersConsult", action = "http://tempuri.org/IService1/PayersConsult")
    @WebResult(name = "PayersConsultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PayersConsult", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.PayersConsult")
    @ResponseWrapper(localName = "PayersConsultResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.PayersConsultResponse")
    public ArrayOfwsSelectPayersByCountryCodeResult payersConsult(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "countryCode", targetNamespace = "http://tempuri.org/")
        String countryCode,
        @WebParam(name = "payerCode", targetNamespace = "http://tempuri.org/")
        String payerCode);

    /**
     * 
     * @param pass
     * @param alias
     * @param remEdo
     * @param user
     * @param pais
     * @return
     *     returns com.lftechnology.gmt.ReceiptTemplate
     */
    @WebMethod(operationName = "GetReceiptData", action = "http://tempuri.org/IService1/GetReceiptData")
    @WebResult(name = "GetReceiptDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReceiptData", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetReceiptData")
    @ResponseWrapper(localName = "GetReceiptDataResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetReceiptDataResponse")
    public ReceiptTemplate getReceiptData(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "rem_edo", targetNamespace = "http://tempuri.org/")
        String remEdo,
        @WebParam(name = "pais", targetNamespace = "http://tempuri.org/")
        String pais);

    /**
     * 
     * @param zip
     * @param pass
     * @param alias
     * @param user
     * @return
     *     returns com.lftechnology.gmt.CityByZip
     */
    @WebMethod(operationName = "GetCityByZip", action = "http://tempuri.org/IService1/GetCityByZip")
    @WebResult(name = "GetCityByZipResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCityByZip", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetCityByZip")
    @ResponseWrapper(localName = "GetCityByZipResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.GetCityByZipResponse")
    public CityByZip getCityByZip(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "zip", targetNamespace = "http://tempuri.org/")
        String zip);

    /**
     * 
     * @param payercode
     * @param receive
     * @param servicecode
     * @param pass
     * @param alias
     * @param ben
     * @param rem
     * @param user
     * @param send
     * @return
     *     returns com.lftechnology.gmt.WsLimitByPayerResult
     */
    @WebMethod(operationName = "CheckPayerLimits", action = "http://tempuri.org/IService1/CheckPayerLimits")
    @WebResult(name = "CheckPayerLimitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckPayerLimits", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.CheckPayerLimits")
    @ResponseWrapper(localName = "CheckPayerLimitsResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.CheckPayerLimitsResponse")
    public WsLimitByPayerResult checkPayerLimits(
        @WebParam(name = "alias", targetNamespace = "http://tempuri.org/")
        String alias,
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "payercode", targetNamespace = "http://tempuri.org/")
        String payercode,
        @WebParam(name = "send", targetNamespace = "http://tempuri.org/")
        Double send,
        @WebParam(name = "receive", targetNamespace = "http://tempuri.org/")
        Double receive,
        @WebParam(name = "servicecode", targetNamespace = "http://tempuri.org/")
        String servicecode,
        @WebParam(name = "ben", targetNamespace = "http://tempuri.org/")
        String ben,
        @WebParam(name = "rem", targetNamespace = "http://tempuri.org/")
        String rem);

    /**
     * 
     * @param fee
     * @param codePromo
     * @return
     *     returns com.lftechnology.gmt.WsSelectPromoResult
     */
    @WebMethod(operationName = "PromotionsCode", action = "http://tempuri.org/IService1/PromotionsCode")
    @WebResult(name = "PromotionsCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PromotionsCode", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.PromotionsCode")
    @ResponseWrapper(localName = "PromotionsCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.lftechnology.gmt.PromotionsCodeResponse")
    public WsSelectPromoResult promotionsCode(
        @WebParam(name = "Code_promo", targetNamespace = "http://tempuri.org/")
        String codePromo,
        @WebParam(name = "Fee", targetNamespace = "http://tempuri.org/")
        Float fee);

}
